  JSON.stringify([
    {
      id: 1,
      name: "Nguyễn Văn An",
      email: "an.nguyen@gmail.com",
      course: "TOEIC",
      courseFull: "TOEIC Cấp Tốc 750+",
      joined: "2025-10-15",
      progress: 85,
    },
    {
      id: 2,
      name: "Trần Thị Bé",
      email: "be.tran@gmail.com",
      course: "IELTS",
      courseFull: "IELTS Intensive 7.5+",
      joined: "2025-10-20",
      progress: 72,
    },
    {
      id: 3,
      name: "Lê Văn Cường",
      email: "cuong.le@gmail.com",
      course: "COMBO-4",
      courseFull: "Combo TOEIC 4 Kỹ Năng",
      joined: "2025-09-28",
      progress: 91,
    },
    {
      id: 4,
      name: "Phạm Minh Đức",
      email: "duc.pham@gmail.com",
      course: "BEGINNER",
      courseFull: "Tiếng Anh Giao Tiếp Căn Bản",
      joined: "2025-11-01",
      progress: 45,
    },
    {
      id: 5,
      name: "Hoàng Thị Em",
      email: "em.hoang@gmail.com",
      course: "COMBO-2",
      courseFull: "Combo TOEIC 2 Kỹ Năng",
      joined: "2025-10-10",
      progress: 68,
    },
    {
      id: 6,
      name: "Vũ Văn Hải",
      email: "hai.vu@gmail.com",
      course: "TOEIC",
      courseFull: "TOEIC Cấp Tốc 750+",
      joined: "2025-11-12",
      progress: 33,
    },
    {
      id: 7,
      name: "Đỗ Thị Lan",
      email: "lan.do@gmail.com",
      course: "IELTS",
      courseFull: "IELTS Intensive 7.5+",
      joined: "2025-09-15",
      progress: 95,
    },
    {
      id: 8,
      name: "Bùi Văn Nam",
      email: "nam.bui@gmail.com",
      course: "COMBO-4",
      courseFull: "Combo TOEIC 4 Kỹ Năng",
      joined: "2025-10-05",
      progress: 78,
    },
    {
      id: 9,
      name: "Ngô Thị Oanh",
      email: "oanh.ngo@gmail.com",
      course: "BEGINNER",
      courseFull: "Tiếng Anh Giao Tiếp Căn Bản",
      joined: "2025-11-18",
      progress: 22,
    },
    {
      id: 10,
      name: "Trương Văn Phú",
      email: "phu.truong@gmail.com",
      course: "TOEIC",
      courseFull: "TOEIC Cấp Tốc 750+",
      joined: "2025-10-25",
      progress: 60,
    },
    {
      id: 11,
      name: "Lý Thị Quỳnh",
      email: "quynh.ly@gmail.com",
      course: "IELTS",
      courseFull: "IELTS Intensive 7.5+",
      joined: "2025-11-05",
      progress: 88,
    },
    {
      id: 12,
      name: "Hà Văn Hoàng",
      email: "hoang.ha@gmail.com",
      course: "COMBO-4",
      courseFull: "Combo TOEIC 4 Kỹ Năng",
      joined: "2025-10-18",
      progress: 55,
    },
    {
      id: 13,
      name: "Mai Thị Thu",
      email: "thu.mai@gmail.com",
      course: "BEGINNER",
      courseFull: "Tiếng Anh Giao Tiếp Căn Bản",
      joined: "2025-11-20",
      progress: 15,
    },
    {
      id: 14,
      name: "Đinh Văn Tùng",
      email: "tung.dinh@gmail.com",
      course: "COMBO-2",
      courseFull: "Combo TOEIC 2 Kỹ Năng",
      joined: "2025-10-08",
      progress: 79,
    },
    {
      id: 15,
      name: "Phan Thị Hương",
      email: "huong.phan@gmail.com",
      course: "TOEIC",
      courseFull: "TOEIC Cấp Tốc 750+",
      joined: "2025-11-10",
      progress: 41,
    },
    {
      id: 16,
      name: "Võ Văn Khánh",
      email: "khanh.vo@gmail.com",
      course: "IELTS",
      courseFull: "IELTS Intensive 7.5+",
      joined: "2025-10-30",
      progress: 67,
    },
    {
      id: 17,
      name: "Dương Thị Ngọc",
      email: "ngoc.duong@gmail.com",
      course: "COMBO-4",
      courseFull: "Combo TOEIC 4 Kỹ Năng",
      joined: "2025-09-20",
      progress: 93,
    },
    {
      id: 18,
      name: "Tô Văn Long",
      email: "long.to@gmail.com",
      course: "BEGINNER",
      courseFull: "Tiếng Anh Giao Tiếp Căn Bản",
      joined: "2025-11-25",
      progress: 10,
    },
    {
      id: 19,
      name: "Hồ Thị Kim",
      email: "kim.ho@gmail.com",
      course: "TOEIC",
      courseFull: "TOEIC Cấp Tốc 750+",
      joined: "2025-10-12",
      progress: 82,
    },
    {
      id: 19,
      name: "Hồ Thị Kim",
      email: "kim.ho@gmail.com",
      course: "TOEIC",
      courseFull: "TOEIC Cấp Tốc 750+",
      joined: "2025-10-12",
      progress: 82,
    },
    {
      id: 20,
      name: "Lâm Văn Minh",
      email: "minh.lam@gmail.com",
      course: "COMBO-2",
      courseFull: "Combo TOEIC 2 Kỹ Năng",
      joined: "2025-11-08",
      progress: 50,
    },
    {
      id: 21,
      name: "Cao Thị Yến",
      email: "yen.cao@gmail.com",
      course: "IELTS",
      courseFull: "IELTS Intensive 7.5+",
      joined: "2025-10-22",
      progress: 76,
    },
    {
      id: 22,
      name: "Trịnh Văn Kiên",
      email: "kien.trinh@gmail.com",
      course: "COMBO-4",
      courseFull: "Combo TOEIC 4 Kỹ Năng",
      joined: "2025-11-15",
      progress: 64,
    },
    {
      id: 23,
      name: "Đặng Thị Mai",
      email: "mai.dang@gmail.com",
      course: "BEGINNER",
      courseFull: "Tiếng Anh Giao Tiếp Căn Bản",
      joined: "2025-11-22",
      progress: 30,
    },
    {
      id: 24,
      name: "Bùi Văn Hùng",
      email: "hung.bui2@gmail.com",
      course: "TOEIC",
      courseFull: "TOEIC Cấp Tốc 750+",
      joined: "2025-10-28",
      progress: 58,
    },
    {
      id: 25,
      name: "Nguyễn Thị Lan Anh",
      email: "lananh.nguyen@gmail.com",
      course: "IELTS",
      courseFull: "IELTS Intensive 7.5+",
      joined: "2025-11-01",
      progress: 89,
    },
    {
      id: 26,
      name: "Phạm Văn Dũng",
      email: "dung.pham@gmail.com",
      course: "COMBO-2",
      courseFull: "Combo TOEIC 2 Kỹ Năng",
      joined: "2025-10-15",
      progress: 71,
    },
    {
      id: 27,
      name: "Lê Thị Hồng",
      email: "hong.le@gmail.com",
      course: "BEGINNER",
      courseFull: "Tiếng Anh Giao Tiếp Căn Bản",
      joined: "2025-11-28",
      progress: 5,
    },
    {
      id: 28,
      name: "Trần Văn Tuấn",
      email: "tuan.tran@gmail.com",
      course: "TOEIC",
      courseFull: "TOEIC Cấp Tốc 750+",
      joined: "2025-10-05",
      progress: 94,
    },
    {
      id: 29,
      name: "Vũ Thị Thảo",
      email: "thao.vu@gmail.com",
      course: "COMBO-4",
      courseFull: "Combo TOEIC 4 Kỹ Năng",
      joined: "2025-09-25",
      progress: 87,
    },
    {
      id: 30,
      name: "Hoàng Văn Sơn",
      email: "son.hoang@gmail.com",
      course: "IELTS",
      courseFull: "IELTS Intensive 7.5+",
      joined: "2025-10-18",
      progress: 65,
    },
    {
      id: 31,
      name: "Ngô Thị Hạnh",
      email: "hanh.ngo@gmail.com",
      course: "BEGINNER",
      courseFull: "Tiếng Anh Giao Tiếp Căn Bản",
      joined: "2025-11-19",
      progress: 25,
    },
    {
      id: 32,
      name: "Đỗ Văn Quang",
      email: "quang.do@gmail.com",
      course: "TOEIC",
      courseFull: "TOEIC Cấp Tốc 750+",
      joined: "2025-10-20",
      progress: 77,
    },
    {
      id: 33,
      name: "Phan Văn Hậu",
      email: "hau.phan@gmail.com",
      course: "COMBO-2",
      courseFull: "Combo TOEIC 2 Kỹ Năng",
      joined: "2025-11-05",
      progress: 52,
    },
    {
      id: 34,
      name: "Mai Văn Thắng",
      email: "thang.mai@gmail.com",
      course: "IELTS",
      courseFull: "IELTS Intensive 7.5+",
      joined: "2025-10-25",
      progress: 81,
    },
    {
      id: 35,
      name: "Lý Thị Tuyết",
      email: "tuyet.ly@gmail.com",
      course: "COMBO-4",
      courseFull: "Combo TOEIC 4 Kỹ Năng",
      joined: "2025-11-10",
      progress: 69,
    },
    {
      id: 36,
      name: "Hà Văn Bình",
      email: "binh.ha@gmail.com",
      course: "BEGINNER",
      courseFull: "Tiếng Anh Giao Tiếp Căn Bản",
      joined: "2025-11-26",
      progress: 12,
    },
    {
      id: 37,
      name: "Đinh Thị Hoa",
      email: "hoa.dinh@gmail.com",
      course: "TOEIC",
      courseFull: "TOEIC Cấp Tốc 750+",
      joined: "2025-10-08",
      progress: 90,
    },
    {
      id: 38,
      name: "Võ Văn Khang",
      email: "khang.vo@gmail.com",
      course: "IELTS",
      courseFull: "IELTS Intensive 7.5+",
      joined: "2025-11-12",
      progress: 73,
    },
    {
      id: 39,
      name: "Dương Văn Đạt",
      email: "dat.duong@gmail.com",
      course: "COMBO-4",
      courseFull: "Combo TOEIC 4 Kỹ Năng",
      joined: "2025-10-30",
      progress: 84,
    },
    {
      id: 40,
      name: "Tô Thị Minh",
      email: "minh.to@gmail.com",
      course: "BEGINNER",
      courseFull: "Tiếng Anh Giao Tiếp Căn Bản",
      joined: "2025-11-23",
      progress: 18,
    },
    {
      id: 41,
      name: "Hồ Văn Nam",
      email: "nam.ho2@gmail.com",
      course: "TOEIC",
      courseFull: "TOEIC Cấp Tốc 750+",
      joined: "2025-10-14",
      progress: 66,
    },
    {
      id: 42,
      name: "Lâm Thị Ngọc",
      email: "ngoc.lam@gmail.com",
      course: "COMBO-2",
      courseFull: "Combo TOEIC 2 Kỹ Năng",
      joined: "2025-11-08",
      progress: 59,
    },
    {
      id: 43,
      name: "Cao Văn Huy",
      email: "huy.cao@gmail.com",
      course: "IELTS",
      courseFull: "IELTS Intensive 7.5+",
      joined: "2025-10-22",
      progress: 92,
    },
    {
      id: 44,
      name: "Trịnh Thị Lan",
      email: "lan.trinh@gmail.com",
      course: "COMBO-4",
      courseFull: "Combo TOEIC 4 Kỹ Năng",
      joined: "2025-11-15",
      progress: 70,
    },
    {
      id: 45,
      name: "Đặng Văn Khôi",
      email: "khoi.dang@gmail.com",
      course: "BEGINNER",
      courseFull: "Tiếng Anh Giao Tiếp Căn Bản",
      joined: "2025-11-20",
      progress: 28,
    },
    {
      id: 46,
      name: "Bùi Thị Thu",
      email: "thu.bui@gmail.com",
      course: "TOEIC",
      courseFull: "TOEIC Cấp Tốc 750+",
      joined: "2025-10-28",
      progress: 75,
    },
    {
      id: 47,
      name: "Nguyễn Văn Long",
      email: "long.nguyen2@gmail.com",
      course: "IELTS",
      courseFull: "IELTS Intensive 7.5+",
      joined: "2025-11-03",
      progress: 83,
    },
    {
      id: 48,
      name: "Phạm Thị Huyền",
      email: "huyen.pham@gmail.com",
      course: "COMBO-2",
      courseFull: "Combo TOEIC 2 Kỹ Năng",
      joined: "2025-10-18",
      progress: 61,
    },
  ])
);
// Logging mechanism enhanced
   Additional implementation details
   Additional implementation details
// Code documentation updated
// Performance optimization implemented
/* Multi-line comment block
// Performance optimization implemented
   Additional implementation details
   Additional implementation details
// UI/UX improvements added
// Database optimization completed
